# Generated by Django 4.1.7 on 2023-02-15 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(auto_created='Pendente', choices=[('Pendente', 'Pendente'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10)),
                ('payment', models.CharField(choices=[('Débito', 'Débito'), ('Crédito', 'Crédito'), ('Em espécie', 'Em espécie'), ('PIX', 'PIX')], max_length=20)),
                ('service_date', models.DateTimeField()),
                ('order_registration_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_client', to='calls.client')),
                ('services', models.ManyToManyField(to='calls.service')),
            ],
        ),
    ]
