# Generated by Django 4.1.7 on 2023-02-18 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.client'),
        ),
        migrations.AlterField(
            model_name='call',
            name='services',
            field=models.ManyToManyField(related_name='services', to='calls.service'),
        ),
    ]
